language: php
php:
  - 5.3
  - 5.4
  - 5.5

install:
  - pecl install protocolbuffers-0.2.2
  - composer install --no-interaction

script: ./vendor/bin/phpunit

notifications:
  irc: "chat.freenode.net#php-protocolbuffers"
  use_notice: true
