-
  match: "^(EnumDescriptorProto|DescriptorProto)$"
  file: "/google/protobuf/$0.php"
  insertion_point: "class_scope:.google.protobuf.$0"
  insertion: |
    /**
     *  helper method for retriviing parent FileDescriptorProto message
     *
     *  @return \google\protobuf\FileDescriptorProto
     */
    public function file()
    {
      $parent = $this->containerOf();
      while ($parent && !($parent instanceof \google\protobuf\FileDescriptorProto)) {
        $parent = $parent->containerOf();
      }
      return $parent;
    }
